export const Categories = [
  {
    htmlFor: "musicCatg",
    inputId: "musicCatg",
    inputName: "music",
    inputValue: "music",
    labelText: "music",
  },
  {
    htmlFor: "natureCatg",
    inputId: "natureCatg",
    inputName: "nature",
    inputValue: "nature",
    labelText: "nature",
  },
  {
    htmlFor: "lifeCatg",
    inputId: "lifeCatg",
    inputName: "life",
    inputValue: "life",
    labelText: "life",
  },
  {
    htmlFor: "foodCatg",
    inputId: "foodCatg",
    inputName: "food",
    inputValue: "food",
    labelText: "food",
  },
  {
    htmlFor: "friendsCatg",
    inputId: "friendsCatg",
    inputName: "friends",
    inputValue: "friends",
    labelText: "friends",
  },
  {
    htmlFor: "memoriesCatg",
    inputId: "memoriesCatg",
    inputName: "memories",
    inputValue: "memories",
    labelText: "memories",
  },
  {
    htmlFor: "journeyCatg",
    inputId: "journeysCatg",
    inputName: "journey",
    inputValue: "journey",
    labelText: "journey",
  },
  {
    htmlFor: "cookingCatg",
    inputId: "cookingCatg",
    inputName: "cooking",
    inputValue: "cooking",
    labelText: "cooking",
  },
  {
    htmlFor: "familyCatg",
    inputId: "familyCatg",
    inputName: "family",
    inputValue: "family",
    labelText: "family",
  },
  {
    htmlFor: "schoolCatg",
    inputId: "schoolCatg",
    inputName: "school",
    inputValue: "school",
    labelText: "school",
  },
  {
    htmlFor: "scienceCatg",
    inputId: "scienceCatg",
    inputName: "science",
    inputValue: "science",
    labelText: "science & technology",
  },
  {
    htmlFor: "astronomyCatg",
    inputId: "astronomyCatg",
    inputName: "astronomy",
    inputValue: "astronomy",
    labelText: "astronomy",
  },
  {
    htmlFor: "medialCatg",
    inputId: "medialCatg",
    inputName: "medial",
    inputValue: "medial",
    labelText: "medial",
  },
  {
    htmlFor: "loveCatg",
    inputId: "loveCatg",
    inputName: "love",
    inputValue: "love",
    labelText: "love",
  },
  {
    htmlFor: "tourCatg",
    inputId: "tourCatg",
    inputName: "tour",
    inputValue: "tour",
    labelText: "tour",
  },
];
